package com.bidify.common.enums;

public enum EventType {
    AUCTION_CREATED,
    AUCTION_UPDATED,
    AUCTION_ENDED,
    BID_PLACED,
    USER_JOINED_AUCTION,
    SERVER_NOTICE,
    ERROR,
    AUCTION_DELETED,
    WALLET_CHANGED,
    LOCKED_BALANCE_CHANGED
}
