package com.bidify.common.enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    LOGOUT,

    GET_PROFILE,
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    GET_ADMIN_USERS,
    PROMOTE_ADMIN,
    DEMOTE_ADMIN,
    BAN_USER,
    UNBAN_USER,
    DELETE_USER,

    CREATE_ITEM,
    GET_MY_INVENTORY,
    GET_USER_INVENTORY,
    GET_ITEM_DETAIL,
    UPDATE_ITEM,
    DELETE_ITEM,

    CREATE_AUCTION,
    UPDATE_AUCTION,
    GET_LIVE_AUCTIONS,
    GET_UPCOMING_AUCTIONS,
    GET_AUCTION_DETAIL,
    DELETE_AUCTION,
    SEARCH_AUCTIONS,

    PLACE_BID,
    SET_AUTO_BID,
    DISABLE_AUTO_BID,
    GET_BID_HISTORY,

    JOIN_AUCTION,
    LEAVE_AUCTION,

    DEPOSIT,
    WITHDRAW,
    GET_TRANSACTION_HISTORY,

    GET_WALLET_REQUEST_HISTORY,
    GET_PENDING_WALLET_REQUESTS,
    REVIEW_WALLET_REQUEST,

    PAY_AUCTION,
    CONFIRM_AUCTION_DELIVERY,
    RESOLVE_AUCTION,
    GET_USER_SETTLEMENTS,
    GET_ADMIN_AUCTIONS,
    GET_MY_AUCTIONS
}
